# action.yml
name: 'Commit Meaning'
description: 'In a paragraph, describe the commits for a PR.'
inputs:
  openai-api-key:  # id of input
    description: 'Your OpenAI API key.'
    required: true
outputs:
  description: # id of output
    description: 'The PR commit log description.'
    value: ${{ steps.get-commit-meaning.outputs.description }}
runs:
  using: 'composite'
  steps:
    - name: Install Python 
      uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash 
    - name: Pass inputs to shell
      run: |
        echo "INPUT_OPENAIAPIKEY=${{ inputs.openai-api-key }}" >> $GITHUB_ENV
      shell: bash 
    - name: Checkout the repo 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get commit meaning
      id: get-commit-meaning 
      run: echo "::set-output name=random-number::$(python main.py)"
      shell: bash
