name: Test Commit Meaning Action
on: [push]

jobs:
  get-commit-meaning:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Returns a description of the latest commits
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the commit meaning
        id: get_commit_meaning
        uses: ./
        with:
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"

      - name: Pring the meaning string
        run: echo ${{ steps.get_commit_meaning.outputs.description }}
        shell: bash

      - name: Add pr comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Description**
            ${{ steps.get_commit_meaning.outputs.description }}
